#data:
  #input: "data/raw/owid-co2-data.csv"
  #processed: "data/raw/raw_co2.csv"
#country: "India"   # change to any country (e.g., "United States", "Germany")
data:
  input: "data/raw/owid-co2-data.csv"
  processed: "data/raw/raw_co2.csv"
api:
  base_url: "https://api.electricitymap.org/v3"
  token: ""        # optional; if empty, fallback to mock
  zone: "IN"
country: "India"
